version: '2'

services:
  nexus3:
    image: hub.qucheng.com/app/nexus3:${TAG:-latest}
    container_name: nexus3
    ports:
      - '8081:8081'
    volumes:
      - 'data:/nexus-data'
    environment:
      # - DEBUG=1
      # - PASSWORD=nexus4Quick0n
      - IS_CONTAINER=true
    networks:
      - net

networks:
  net:
    driver: bridge

# persistence
volumes:
  data:
    driver: local
